config/routes.rb
Rails.application.routes.draw do
 resources :contatos do
    collection { post :import }
  end
  root to: 'login#index'
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contato.rb
class Contato < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }

  validates :telefone,:presence => true,
                 :numericality => true,
                 :length => { :minimum => 10, :maximum => 15 }
  validates :email, uniqueness: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Contato.create! row.to_hash
    end
  end
end

app/models/usuario.rb
class Usuario < ApplicationRecord

  validates :senha, presence: true, length: { minimum: 6 }
  validates :nome, presence: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :load_user
   protect_from_forgery with: :exception
  def index
  end

  def load_user
    if session[:usuario_id]
      @online = Usuario.find(session[:usuario_id])
    end
  end

  def logout
    reset_session
    redirect_to :controller => '/login', :action => 'index'
  end
end

app/controllers/contatos_controller.rb
require 'csv'
class ContatosController < ApplicationController

  before_action :validate_login
  before_action :set_contato, only: [:show, :edit, :update, :destroy]

  def validate_login
    if @online.eql? nil
      redirect_to :controller => '/login', :action => 'index'
    else
      return true
    end
  end

  # GET /contatos
  # GET /contatos.json
  def index
    @contatos = Contato.all
  end

  # GET /contatos/1
  # GET /contatos/1.json
  def show
  end

  # GET /contatos/new
  def new
    @contato = Contato.new
  end

  # GET /contatos/1/edit
  def edit
  end

  # POST /contatos
  # POST /contatos.json
  def create
    @contato = Contato.new(contato_params)

    respond_to do |format|
      if @contato.save
        format.html { redirect_to @contato, notice: 'Contato was successfully created.' }
        format.json { render :show, status: :created, location: @contato }
      else
        format.html { render :new }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contatos/1
  # PATCH/PUT /contatos/1.json
  def update
    respond_to do |format|
      if @contato.update(contato_params)
        format.html { redirect_to @contato, notice: 'Contato was successfully updated.' }
        format.json { render :show, status: :ok, location: @contato }
      else
        format.html { render :edit }
        format.json { render json: @contato.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contatos/1
  # DELETE /contatos/1.json
  def destroy
    @contato.destroy
    respond_to do |format|
      format.html { redirect_to contatos_url, notice: 'Contato was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def import
    Contato.import(params[:file])
    redirect_to :controller => '/contatos', :action => 'index'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contato
      @contato = Contato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contato_params
      params.require(:contato).permit(:nome, :email, :telefone)
    end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
  end

  def index_do
    form     = params[:form]
    usuario = Usuario.find_by_nome_and_senha(form[:login],form[:senha])
    if not usuario.nil?
        session[:usuario_id] = usuario.id
        redirect_to :controller => '/contatos', :action => 'index'
    else
      if usuario.nil?
        flash[:error] = "Usuario Não cadastrado"
      else
        flash[:error] = "Usuario Não tem Acesso"
      end
      redirect_to :controller => '/login', :action => 'index'
    end
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :senha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contatos_helper.rb
module ContatosHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/contatos/_form.html.erb
<%= form_with(model: contato, local: true) do |form| %>
  <% if contato.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contato.errors.count, "error") %> prohibited this contato from being saved:</h2>

      <ul>
      <% contato.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :contato_nome %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contato_email %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone, id: :contato_telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contatos/edit.html.erb
<h1>Editing Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Show', @contato %> |
<%= link_to 'Back', contatos_path %>

app/views/contatos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Email</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contatos.each do |contato| %>
      <tr>
        <td><%= contato.nome %></td>
        <td><%= contato.email %></td>
        <td><%= contato.telefone %></td>
        <td><%= link_to 'Show', contato %></td>
        <td><%= link_to 'Edit', edit_contato_path(contato) %></td>
        <td><%= link_to 'Destroy', contato, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contato', new_contato_path %>



<h2>Importar Contatos</h2>

<%= form_tag import_contatos_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar" %>
<% end %>

app/views/contatos/new.html.erb
<h1>New Contato</h1>

<%= render 'form', contato: @contato %>

<%= link_to 'Back', contatos_path %>

app/views/contatos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @contato.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contato.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @contato.telefone %>
</p>

<%= link_to 'Edit', edit_contato_path(@contato) %> |
<%= link_to 'Back', contatos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testeknowe</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <p>
  <%= "Olá #{@online.try(:nome)}" unless @online.eql? nil  %>
  <% unless @online.eql? nil %>
    <a href="<%= url_for :controller => 'application', :action => 'logout' -%>">Logout</a>
    <%= link_to 'Usuarios', usuarios_path %>
    <%= link_to 'Contatos', contatos_path %>
  <%end%>
  </p>
  <body>
    <%= yield %>
  </body>
</html>

app/views/login/index.html.erb
  <form action="/login/index_do">
    <table>
      <tr>
        <td>Login:</td>
        <td><input type="text" name="form[login]" value=""><br></td>
      </tr>
      <tr>
        <td>Senha:</td>
        <td><input type="password" name="form[senha]" value=""><br></td>
      </tr>
      <tr>
        <td>
          <a href="<%= url_for :controller => 'usuarios', :action => 'new' -%>">Cadastro</a>
        </td>
        <td align="right"><input type="submit" value="Entre"></td>
      </tr>
    </table>
  </form>

app/views/usuarios/_form.html.erb
<%= form_with(model: usuario, local: true) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome, id: :usuario_nome %>
  </div>

  <div class="field">
    <%= form.label :senha %>
    <%= form.text_field :senha, id: :usuario_senha %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Senha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.senha %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @usuario.senha %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>